services:
  crate:
    container_name: crate-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: crate-backend:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
