version: "3.9"
services:
  crate-database:
    image: neo4j:latest
    hostname: neo4j
    container_name: crate-database
    volumes:
      - ./db/conf:/conf
      - ./db/data:/data
      - ./db/import:/import
      - ./db/logs:/logs
      - ./db/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/averysecurepassword
    ports:
        - "7474:7474"
        - "7687:7687"
    networks:
      - spring-cloud-network

  crate:
    container_name: crate-backend
    build: .
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    environment:
      - NEO4J_AUTH_USERNAME=neo4j
      - NEO4J_AUTH_PASSWORD=averysecurepassword
      - DB_SERVER=crate-database
      - DB_PORT=7687
    depends_on:
      - crate-database

networks:
  spring-cloud-network:
    name: spring-cloud-network
    driver: bridge
#    external: true
