version: "3.9"
services:
  crate:
    container_name: crate-backend
    build: .
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    name: spring-cloud-network
#    external: true
